### ISSUE TITLE
value of Epsilon_ref in table 1

### ISSUE THREAD

**Issue by liangbright** [ZiangYan/deepdefense.pytorch#4]
Hi Ziang Yan,

What is the value of Epsilon_ref in table 1 ?

Best,
Liang

**Comment by ZiangYan** [comment]
Hi,

Please see the table below for MNIST and CIFAR-10 epsilon ref values.

| Dataset | Arch | Epsilon ref |
|:----------:|:------:|:---------------:|
| MNIST | MLP | 35.16 |
| MNIST | LeNet | 53.98 |
| CIFAR-10 | ConvNet | 2.75 |
| CIFAR-10 | NIN | 3.75 |

Please also note the evaluation protocol differs from the current common practice in two aspects:

1. The epsilon values are calculated on the processed images instead of the raw image (i.e., in [0, 1] or [0, 255] range) and the pre-processing procedure are somewhat non-standard (see #3 for more details).
2. The perturbed images are not clipped back to the valid image domain.
